package Utilities.SearchPresentOptions;

public enum Category {
    BEST2022,
    GIFT_TO_HOUSE,
    GIFT_CARD_FASHION,
    GIFT_CARD_BREAKFAST,
    GIFT_CARD_SHEFF,
    GIFT_CARD_MOTHER_AND_BABY,
    GIFT_CARD_SPA,
    GIFT_CARD_RESTAURANT,
    GIFT_CARD_LOCAL_GIFT,
    GIFT_CARD_CULINARY,
    GIFT_CARD_HOME_KITCHEN_GADGETS,
    GIFT_CARD_HEALTH_SPORT_EXTREME,
    GIFT_CARD_MUTUAL_EXPERIENCES,
    GIFT_CARD_VOCATIONS_HOTELS,
    GIFT_CARD_CULTURE,
    GIFT_CARD_BEAUTY,
    GIFT_CARD_ESCAPE_ROOMS,
    GIFT_CARD_WORKSHOP;
}
